// Command sealmsg encrypts the final message and generates the release key
// file. Run it from the repository root (make seal / make release).
//
// Files it reads and writes:
//
//	.final_message.key        master key, hex (local only, gitignored)
//	assets/final_message.txt  your plaintext message (local only, gitignored)
//	assets/final_message.enc  sealed message (committed)
//	assets/key_release.go     key for -tags release builds (local only, gitignored)
package main

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"os"
	"strings"

	"lastdose/internal/secret"
)

const (
	keyFile   = ".final_message.key"
	plainFile = "assets/final_message.txt"
	sealFile  = "assets/final_message.enc"
	goKeyFile = "assets/key_release.go"
)

func main() {
	keyOnly := flag.Bool("key-only", false, "only regenerate "+goKeyFile+" from "+keyFile)
	flag.Parse()
	if err := run(*keyOnly); err != nil {
		fmt.Fprintln(os.Stderr, "sealmsg:", err)
		os.Exit(1)
	}
}

func run(keyOnly bool) error {
	key, created, err := loadKey(!keyOnly)
	if err != nil {
		return err
	}
	if created {
		fmt.Printf("created %s: back it up, every release must use the same key\n", keyFile)
	}
	if !keyOnly {
		plain, err := os.ReadFile(plainFile)
		if err != nil {
			return err
		}
		plain = bytes.TrimSpace(plain)
		if len(plain) == 0 {
			return errors.New(plainFile + " is empty")
		}
		sealed, err := secret.Seal(key, plain)
		if err != nil {
			return err
		}
		if err := os.WriteFile(sealFile, sealed, 0o644); err != nil {
			return err
		}
		fmt.Printf("sealed %s -> %s (%d bytes)\n", plainFile, sealFile, len(sealed))
	}
	if err := writeGoKey(key); err != nil {
		return err
	}
	fmt.Println("wrote", goKeyFile)
	return nil
}

// loadKey reads the master key, creating it when allowed and missing.
func loadKey(create bool) ([]byte, bool, error) {
	b, err := os.ReadFile(keyFile)
	switch {
	case err == nil:
		key, err := hex.DecodeString(strings.TrimSpace(string(b)))
		if err != nil || len(key) != secret.KeySize {
			return nil, false, fmt.Errorf("%s: want %d hex-encoded bytes", keyFile, secret.KeySize)
		}
		return key, false, nil
	case errors.Is(err, os.ErrNotExist) && create:
		key, err := secret.NewKey()
		if err != nil {
			return nil, false, err
		}
		return key, true, os.WriteFile(keyFile, []byte(hex.EncodeToString(key)+"\n"), 0o600)
	case errors.Is(err, os.ErrNotExist):
		return nil, false, fmt.Errorf("%s not found: run `make seal` first, or restore it from your backup", keyFile)
	}
	return nil, false, err
}

// writeGoKey stores the key XOR-masked, so it does not sit in the binary as
// one plain run of bytes. This is obfuscation only; see README.
func writeGoKey(key []byte) error {
	mask := make([]byte, len(key))
	if _, err := rand.Read(mask); err != nil {
		return err
	}
	masked := make([]byte, len(key))
	for i := range key {
		masked[i] = key[i] ^ mask[i]
	}
	src := fmt.Sprintf(`// Code generated by cmd/sealmsg. DO NOT EDIT. DO NOT COMMIT.

//go:build release

package assets

var keyMasked = %#v

var keyMask = %#v

func key() []byte {
	k := make([]byte, len(keyMasked))
	for i := range k {
		k[i] = keyMasked[i] ^ keyMask[i]
	}
	return k
}
`, masked, mask)
	return os.WriteFile(goKeyFile, []byte(src), 0o600)
}
