// Package assets embeds the sealed final message and, in release builds, the
// key that opens it.
//
// The plaintext never enters the repository: only final_message.enc is
// committed. The key is compiled in from key_release.go, a gitignored file
// generated by cmd/sealmsg, and only with -tags release. Builds from public
// sources have no key, so they cannot open the message or sign state.
package assets

import (
	_ "embed"
	"errors"
	"strings"

	"lastdose/internal/secret"
)

//go:embed final_message.enc
var sealed []byte

// ErrNoKey means this binary was built without the release key.
var ErrNoKey = errors.New("this build has no key for the sealed message")

// Key returns the release master key, or nil in builds without it.
func Key() []byte { return key() }

// FinalMessage decrypts the congratulation shown after the last badge.
func FinalMessage() (string, error) {
	k := key()
	if k == nil {
		return "", ErrNoKey
	}
	b, err := secret.Open(k, sealed)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(b)), nil
}
